### ISSUE TITLE
你好，不支持Swift吗？

### ISSUE THREAD

**Issue by github410117** [STShenZhaoliang/STPickerView#23]
`Dependency "STPickerView" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/STShenzhaoliang/STPickerView/issues/new`

**Comment by szlsay** [comment]
platform :ios, "8.0"
use_frameworks!
target 'TestPicker' do
pod 'STPickerView', '~> 2.1'
end

在Podfile中添加use_frameworks!
