### ISSUE TITLE
根本不能用

### ISSUE THREAD

**Issue by lmh0921** [STShenZhaoliang/STPickerView#3]
直接崩在这： _lineView = [[UIView alloc]initWithFrame:CGRectMake(lineX, lineY, lineW, lineH)];

报错Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 0; nan 0.5]'

**Comment by lmh0921** [comment]
你这用了好多.x,.y.top......然后和masonry冲突，.....耦合性好大。。。

**Comment by szlsay** [comment]
masonry 和 UIView的扩展 是有命名冲突，你可以将 扩展的属性前加个前缀 如 x 改为 st_x
